name: Deploy

on:
  pull_request:
    branches: [ "main" ]
#  push:
#    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TZ: 'America/Sao_Paulo'

    steps:
      - name: 🔥 Configuring checkout
        uses: actions/checkout@v4

      # Build Frontend
      - name: 📄 Making .env file
        run: |
          echo "${{ secrets.ENV_FRONTEND_PRODUCTION }}" > resources/frontend-v2/.env

      - name: 🛠️ Installing Node dependencies
        run: cd resources/frontend-v2 && npm install

      - name: 📦 Building application
        run: cd resources/frontend-v2 && npm run build

      # Rodando etapas no servidor
      - name: 📂 Deploy Backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.SSH_APP_PATH }}
            docker exec -it mfp_app bash -c "php artisan down"
            git pull ${{ secrets.SSH_GIT_PULL_URL }}
            docker exec -it mfp_app bash -c "composer update --no-dev"
            docker exec -it mfp_app bash -c "php artisan migrate:all-tenants"

      # Copiando arquivos para o servidor
      - name: 📂 Deploy Frontend
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          local-dir: ./public/build-ionic/
          server-dir: ${{ secrets.SSH_APP_PATH }}public/build-ionic/
          dangerous-clean-slate: true

      # Liberando Servidor
      - name: 🛠️ Finishing Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.SSH_APP_PATH }}
            docker exec -it mfp_app bash -c "php artisan up"
