name: Main Branch Process

on:
  push:
    branches: [ "main" ]

jobs:
  back-end-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Copiando .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Instalando dependências
      run: composer install
    - name: Gerando chave da aplicação
      run: php artisan key:generate
    - name: Aplicando permissões
      run: chmod -R 777 storage bootstrap/cache
    - name: Executando testes via PHPUnit
      run: composer run test:unit
    - name: Gerando tag de cobertura de testes
      uses: timkrase/phpunit-coverage-badge@v1.2.1
      with:
        coverage_badge_path: output/coverage.svg
        push_badge: false
    - name: Upload tag de cobertura de testes para Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./clover.xml